import {
    db,
    productsAPI,
    categoriesAPI,
    usersAPI,
    settingsAPI,
} from "@/lib/database";
import type { Product, Category, User } from "@/types";
const categories: Category[] = [
    {
        id: "cat-1",
        name: "Стратегические игры",
        slug: "strategy",
        description: "Глубокие стратегические игры для тех, кто любит думать",
        icon: "Chess",
        image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
        count: 0,
    },
    {
        id: "cat-2",
        name: "Семейные игры",
        slug: "family",
        description: "Игры для всей семьи и компании друзей",
        icon: "Users",
        image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
        count: 0,
    },
    {
        id: "cat-3",
        name: "Карточные игры",
        slug: "card-games",
        description: "Увлекательные карточные игры на любой вкус",
        icon: "Cards",
        image: "https://images.unsplash.com/photo-1464983953574-0892a716854b",
        count: 0,
    },
    {
        id: "cat-4",
        name: "Партийные игры",
        slug: "party",
        description: "Веселые игры для больших компаний",
        icon: "PartyPopper",
        image: "https://images.unsplash.com/photo-1503676382389-4809596d5290",
        count: 0,
    },
    {
        id: "cat-5",
        name: "Кооперативные игры",
        slug: "cooperative",
        description: "Играйте вместе против игры",
        icon: "Handshake",
        image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353",
        count: 0,
    },
    {
        id: "cat-6",
        name: "Детективы",
        slug: "detective",
        description: "Расследуйте преступления и разгадывайте загадки",
        icon: "Search",
        image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
        count: 0,
    },
    {
        id: "cat-7",
        name: "Экономические",
        slug: "economic",
        description: "Стройте империи и управляйте ресурсами",
        icon: "Coins",
        image: "https://images.unsplash.com/photo-1503676382389-4809596d5290",
        count: 0,
    },
    {
        id: "cat-8",
        name: "Аксессуары",
        slug: "accessories",
        description: "Кубики, протекторы, органайзеры и многое другое",
        icon: "Dices",
        image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
        count: 0,
    },
];
const products: Product[] = [
    {
        id: "prod-1",
        name: "Магическое Противостояние",
        description: "Стратегическая карточная игра для двух игроков",
        fullDescription: "Погрузитесь в мир магии и стратегии! Соберите свою уникальную колоду из сотен доступных карт, каждая из которых обладает особыми способностями. Призывайте существ, применяйте заклинания и используйте артефакты, чтобы одержать победу над противником. Игра требует тактического мышления и умения предугадывать ходы оппонента.",
        price: 1299,
        originalPrice: 1599,
        discount: 19,
        image: "https://images.unsplash.com/photo-1464983953574-0892a716854b",
        category: "Карточные игры",
        subcategories: ["Стратегия", "Фэнтези"],
        tags: ["новинка", "популярное", "скидка", "2 игрока"],
        players: { min: 2, max: 2 },
        ageRating: 12,
        duration: 45,
        difficulty: "Средняя",
        publisher: "GameVerse",
        designer: "Александр Петров",
        year: 2024,
        language: "Русский",
        stock: 15,
        sku: "MGC-001",
        rating: 4.8,
        reviewsCount: 245,
        isNew: true,
        isPopular: true,
        isFeatured: true,
        createdAt: new Date("2024-01-15"),
    },
    {
        id: "prod-2",
        name: "Покер Делюкс",
        description: "Профессиональный набор для игры в покер",
        fullDescription: "Премиальный набор для настоящих ценителей покера. В комплекте: 500 качественных пластиковых карт с защитным покрытием, 500 профессиональных фишек с весом 11.5г, дилерский баттон, таймер и элегантный кожаный кейс. Идеально подходит как для домашних игр, так и для турниров.",
        price: 3499,
        image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353",
        category: "Карточные игры",
        subcategories: ["Покер", "Азартные"],
        tags: ["премиум", "бестселлер", "профессиональный"],
        players: { min: 2, max: 8 },
        ageRating: 18,
        duration: 90,
        difficulty: "Средняя",
        publisher: "PokerPro",
        year: 2023,
        language: "Международный",
        // МАЛФОРМИРОВАННЫЙ ОБЪЕКТ УДАЛЁН ДЛЯ СБОРКИ
    },
        // МАЛФОРМИРОВАННЫЙ ОБЪЕКТ УДАЛЁН ДЛЯ СБОРКИ
    {
        id: "prod-5",
        name: "Битва Королей",
        description: "Тактическая игра для двух игроков",
        fullDescription: `Эпическая война за трон! Управляйте армиями разных фракций, каждая из которых имеет уникальные 
    юниты и способности. Тактически размещайте войска на поле боя, используйте местность и специальные карты событий. 
    Красивые миниатюры и продуманный баланс делают каждую партию уникальной.`,
        price: 1799,
        originalPrice: 2299,
        discount: 22,
        originalPrice: 2299,
        discount: 22,
        image: "https://images.unsplash.com        images: [s:
        ],
        category: "Стратегические игры",
        subcategories: ["Тактика", "Война"],
        tags: ["новинка", "скидка", "2 игрока", "миниатюры"],
        players: { min: 2, max: 2 },
        ageRating: 12,
        duration: 60,
        difficulty: "Средняя",
        publisher: "CMON",
        designer: "Эрик Лэнг",
        year: 2024,
        language: "Русский",
        stock: 20,
        sku: "BTL-KNG-001",
        rating: 4.7,
        reviewsCount: 156,
        isNew: true,
    },
    {
        id: "prod-6",
        name: "Нарды Люкс",
        description: "Роскошные нарды ручной работы",
        fullDescription: `Элитные нарды премиум класса из натурального дерева с инкрустацией перламутром. 
    Каждая доска изготовлена вручную мастерами. В комплекте: деревянная доска, 30 фишек из натурального камня, 
    кубики из слоновой кости (имитация), кожаный стаканчик. Идеальный подарок для ценителей классических игр.`,
        price: 4999,
        originalPrice: 6499,
        discount: 23,
        image: "https://images.unsplash.com        category: "Стратегические игры",
        subcategories: ["Классика", "Нарды"],
        tags: ["премиум", "скидка", "классика", "ручная работа"],
        players: { min: 2, max: 2 },
        ageRating: 10,
        duration: 45,
        difficulty: "Средняя",
        publisher: "LuxuryGames",
        year: 2023,
        language: "Международный",
        stock: 8,
        sku: "NRDY-LUX-001",
        rating: 4.9,
        reviewsCount: 89,
        isFeatured: true,
    },
    {
        id: "prod-7",
        name: "Королевство Кубиков",
        description: "Динамичная игра с кубиками для всей семьи",
        fullDescription: `Бросайте кубики и стройте своё королевство! Простые правила, быстрая игра и множество стратегий 
    делают эту игру идеальной для семейного досуга. Собирайте ресурсы, стройте здания и первым создайте процветающее королевство.`,
        price: 899,
    делают эту игру идеальной для семейного досуга. Собирайте ресурсы, стройте здания и первым создайте процветающее королевство.`,
        price: 899,
        image: "https://images.unsplash.com        images: [s:
        ],
        category: "Семейные игры",
        subcategories: ["Кубики", "Стратегия"],
        tags: ["популярное", "семейная", "быстрая игра"],
        players: { min: 2, max: 6 },
        ageRating: 8,
        duration: 30,
        difficulty: "Легкая",
        publisher: "Hobby World",
        designer: "Том Ленманн",
        year: 2023,
        language: "Русский",
        stock: 28,
        sku: "KNG-DICE-001",
        rating: 4.6,
        reviewsCount: 189,
        isPopular: true,
    },
    {
        id: "prod-8",
        name: "Словесная Магия",
        description: "Составляйте слова и получайте очки",
        fullDescription: `Классическая игра в слова в новом исполнении! Составляйте слова из букв на игровом поле, 
    используйте бонусные клетки для удвоения и утроения очков. Расширьте свой словарный запас и победите соперников!`,
        price: 1199,
    используйте бонусные клетки для удвоения и утроения очков. Расширьте свой словарный запас и победите соперников!`,
        price: 1199,
        image: "https://images.unsplash.com        category: "Семейные игры",зовательная", "классика"],
        players: { min: 2, max: 4 },
        ageRating: 10,
        duration: 45,
        difficulty: "Средняя",
        publisher: "Hasbro",
        year: 2022,
        language: "Русский",
        stock: 35,
        sku: "WRD-MGC-001",
        rating: 4.5,
        reviewsCount: 278,
        isPopular: true,
    },
    {
        id: "prod-9",
        name: "Башня Баланса",
        description: "Испытайте свою ловкость",
        fullDescription: `Классическая игра на ловкость! Аккуратно вытаскивайте блоки из башни и кладите их наверх. 
    Тот, при ком башня упадет, проигрывает. Отличная игра для развития мелкой моторики и концентрации внимания.`,
        price: 599,
        image: "https://images.unsplash.com        category: "Семейные игры",
        subcategories: ["Ловкость", "Веселье"],
        tags: ["популярное", "для детей", "вечеринка"],
        players: { min: 2, max: 6 },
        ageRating: 6,
        duration: 20,
        difficulty: "Легкая",
        publisher: "Hasbro",
        year: 2021,
        language: "Международный",
        stock: 42,
        rating: 4.4,
        reviewsCount: 412,
        isPopular: true,
    },
    {
        id: "prod-10",
        name: "Вечер Игр",
        description: "Сборник мини-игр для весёлой компании",
        fullDescription: `Более 50 различных мини-игр в одной коробке! Викторины, рисование, пантомимы, ассоциации и многое другое. 
    Идеально для вечеринок и больших компаний. Веселье гарантировано!`,
        price: 1499,
        image: "https://images.unsplash.com        category: "Партийные игры",
        subcategories: ["Вечеринка", "Веселье"],
        tags: ["новинка", "популярное", "вечеринка", "большая компания"],
        players: { min: 4, max: 10 },
        ageRating: 16,
        duration: 60,
        difficulty: "Легкая",
        publisher: "GameNight",
        year: 2024,
        language: "Русский",
        stock: 22,
        sku: "GAME-NGT-001",
        rating: 4.7,
        reviewsCount: 389,
        isNew: true,
        isPopular: true,
    },
    {
        id: "prod-11",
        name: "Домино Премиум",
        description: "Классическое домино из натурального дерева",
        fullDescription: `Элегантное домино ручной работы из благородного дерева. Каждая костяшка отполирована вручную и 
    покрыта защитным лаком. Поставляется в деревянной коробке с гравировкой. Отличный подарок для ценителей классики.`,
        price: 1299,
        image: "https://images.unsplash.com        category: "Семейные игры",
        subcategories: ["Классика", "Домино"],
        tags: ["классика", "премиум", "ручная работа"],
        players: { min: 2, max: 4 },
        ageRating: 6,
        duration: 30,
        difficulty: "Легкая",
        publisher: "WoodCraft",
        year: 2023,
        language: "Международный",
        stock: 30,
        sku: "DMN-PREM-001",
        rating: 4.6,
        reviewsCount: 145,
        isFeatured: true,
    },
    {
        id: "prod-12",
        name: "Побег из Замка",
        description: "Кооперативная игра на выживание",
        fullDescription: `Вы оказались в ловушке в проклятом замке! Работайте вместе с другими игроками, чтобы найти выход. 
    Исследуйте комнаты, решайте головоломки, избегайте ловушек и монстров. Только сплоченная команда сможет выбраться живой!`,
        price: 1899,
        image: "https://images.unsplash.com        category: "Кооперативные игры",
        subcategories: ["Хоррор", "Приключения"],
        tags: ["новинка", "кооператив", "атмосферная"],
        players: { min: 2, max: 6 },
        ageRating: 14,
        duration: 90,
        difficulty: "Средняя",
        publisher: "Horror Games",
        designer: "Анна Смирнова",
        year: 2024,
        language: "Русский",
        stock: 18,
        sku: "ESC-CSTL-001",
        rating: 4.8,
        reviewsCount: 234,
        isNew: true,
    },
    {
        id: "prod-13",
        name: "Шерлок: Дело о Кровавом Алмазе",
        description: "Детективная игра для настоящих сыщиков",
        fullDescription: `Станьте великим детективом! Расследуйте загадочное убийство, связанное с пропажей легендарного алмаза. 
    Собирайте улики, допрашивайте свидетелей, анализируйте информацию. Сможете ли вы разгадать все тайны и найти убийцу?`,
        price: 1699,
        image: "https://images.unsplash.com        category: "Детективы",
        subcategories: ["Расследование", "Детектив"],
        tags: ["новинка", "атмосферная", "логика"],
        players: { min: 1, max: 4 },
        ageRating: 14,
        duration: 120,
        difficulty: "Сложная",
        publisher: "Detective Games",
        year: 2024,
        language: "Русский",
        stock: 25,
        sku: "SHRLK-BLD-001",
        rating: 4.9,
        reviewsCount: 167,
        isNew: true,
        isFeatured: true,
    },
    {
        id: "prod-14",
        name: 'Набор RPG Кубиков "Дракон"',
        description:
            "Профессиональный набор кубиков для настольных ролевых игр",
        fullDescription: `Великолепный набор из 7 кубиков (d4, d6, d8, d10, d10%, d12, d20) с драконьим дизайном. 
    Изготовлены из высококачественной смолы с включениями, имитирующими драконью чешую. Поставляются в кожаном чехле с вышивкой.`,
        price: 899,
    Изготовлены из высококачественной смолы с включениями, имитирующими драконью чешую. Поставляются в кожаном чехле с вышивкой.`,
        price: 899,
        image: "https://images.unsplash.com        images: [s:
        ],
        category: "Аксессуары",
        subcategories: ["RPG", "Кубики"],
        tags: ["популярное", "RPG", "аксессуары", "премиум"],
        players: { min: 2, max: 8 },
        ageRating: 12,
        duration: 0,
        difficulty: "Средняя",
        publisher: "DiceEmporium",
        year: 2023,
        language: "Международный",
        stock: 45,
        sku: "DICE-RPG-DRG-001",
        rating: 4.9,
        reviewsCount: 178,
        isPopular: true,
    },
    {
        id: "prod-15",
        name: "Покерные Фишки Премиум (500 шт)",
        description: "Набор профессиональных покерных фишек",
        fullDescription: `Профессиональный набор из 500 покерных фишек весом 11.5г каждая. Керамическое покрытие, 
    5 номиналов разных цветов. Поставляется в алюминиевом кейсе с замком. В комплекте 2 колоды карт и дилерский баттон.`,
        price: 1899,
        image: "https://images.unsplash.com        category: "Аксессуары",
        subcategories: ["Покер", "Фишки"],
        tags: ["премиум", "аксессуары", "профессиональный"],
        players: { min: 2, max: 10 },
        ageRating: 18,
        duration: 0,
        difficulty: "Легкая",
        publisher: "PokerPro",
        year: 2023,
        language: "Международный",
        stock: 18,
        sku: "CHIP-PRO-500",
        rating: 4.8,
        reviewsCount: 234,
        isFeatured: true,
    },
    {
        id: "prod-16",
        name: "Тасовальная Машинка",
        description: "Автоматическая тасовальная машинка для карт",
        fullDescription: `Профессиональная автоматическая тасовальная машинка. Работает от батареек, тасует до 2 колод одновременно. 
    Компактный дизайн, тихая работа. Идеально для покера, блэкджека и других карточных игр.`,
        price: 699,
        originalPrice: 899,
        discount: 22,
        image: "https://images.unsplash.com        category: "Аксессуары",
        subcategories: ["Карты", "Техника"],
        tags: ["скидка", "аксессуары", "удобство"],
        players: { min: 2, max: 10 },
        ageRating: 8,
        duration: 0,
        difficulty: "Легкая",
        publisher: "CardTech",
        year: 2023,
        language: "Международный",
        stock: 52,
        sku: "SHFL-AUTO-001",
        rating: 4.4,
        reviewsCount: 203,
    },
    {
        id: "prod-17",
        name: "Игровой Коврик XL",
        description: "Большой игровой коврик для настольных игр",
        fullDescription: `Профессиональный игровой коврик размером 90x60см из неопрена. Не скользит, защищает игровое поле, 
    поглощает звук кубиков и карт. Легко скручивается для хранения. Подходит для любых настольных игр.`,
        price: 799,
        image: "https://images.unsplash.com        category: "Аксессуары",
        subcategories: ["Коврики", "Защита"],
        tags: ["аксессуары", "удобство", "защита"],
        players: { min: 1, max: 10 },
        ageRating: 6,
        duration: 0,
        difficulty: "Легкая",
        publisher: "GameGear",
        year: 2023,
        language: "Международный",
        stock: 38,
        sku: "MAT-XL-001",
        rating: 4.7,
        reviewsCount: 156,
    },
    {
        id: "prod-18",
        name: "Маджонг Делюкс",
        description: "Традиционная китайская игра маджонг",
        fullDescription: `Роскошный набор маджонга премиум класса. 144 костяшки из высококачественного пластика с традиционными 
    символами. В комплекте игровой коврик, кубики, счетные палочки и подробные правила на русском языке.`,
        price: 2999,
    символами. В комплекте игровой коврик, кубики, счетные палочки и подробные правила на русском языке.`,
        price: 2999,
        image: "https://images.unsplash.com        category: "Стратегические игры",ассика"],
        players: { min: 3, max: 4 },
        ageRating: 12,
        duration: 90,
        difficulty: "Сложная",
        publisher: "MahjongPro",
        year: 2024,
        language: "Русский",
        stock: 15,
        sku: "MHJNG-DLX-001",
        rating: 4.8,
        reviewsCount: 124,
        isNew: true,
    },
        isNew: true,
    },
    {
        id: "prod-19",
        name: "Магический Лес - Пазл 1000 деталей",тва! Красочный пазл из 1000 деталей с изображением магического леса, 
    населенного мистическими существами. Высококачественная печать, плотный картон, точная подгонка деталей.`,
        price: 799,
    населенного мистическими существами. Высококачественная печать, плотный картон, точная подгонка деталей.`,
        price: 799,
        originalPrice: 999,
        discount: 20,
        image: "https://images.unsplash.com        category: "Пазлы",красивый", "для всех"],
        players: { min: 1, max: 4 },
        ageRating: 12,
        duration: 180,
        difficulty: "Средняя",
        publisher: "PuzzleArt",
        year: 2023,
        language: "Международный",
        stock: 25,
        sku: "PZL-FRST-1000",
        rating: 4.6,
        reviewsCount: 167,
    },
    {
        id: "prod-20",
        name: "Космическая Одиссея - Пазл 2000 деталей",
        description: "Сложный пазл с космическим пейзажем",
        fullDescription: `Для настоящих ценителей сложных пазлов! 2000 деталей, детальное изображение космических просторов 
    с планетами, туманностями и звездными скоплениями. Размер готового пазла 98x68см.`,
        price: 1299,
    с планетами, туманностями и звездными скоплениями. Размер готового пазла 98x68см.`,
        price: 1299,
        image: "https://images.unsplash.com        category: "Пазлы","красивый", "большой"],
        players: { min: 1, max: 4 },
        ageRating: 14,
        duration: 300,
        difficulty: "Сложная",
        publisher: "PuzzleArt",
        year: 2023,
        language: "Международный",
        stock: 18,
        sku: "PZL-SPC-2000",
        rating: 4.8,
        reviewsCount: 89,
        isFeatured: true,
    },
];
const users: User[] = [
    {
        id: "user-admin",
        email: "admin@boardgames.com",
        password: "admin123", 
        name: "Администратор",
        id: "user-admin",
        email: "admin@boardgames.com",
        password: "admin123",
        name: "Администратор",
        points: 5000,
        ordersCount: 0,
        createdAt: new Date("2023-01-01"),
    },
    {
        id: "user-test",
        email: "user@test.com",
        password: "user123", 
        name: "Тестовый Пользователь",
        id: "user-test",
        email: "user@test.com",
        password: "user123",
        name: "Тестовый Пользователь",
        points: 450,
        ordersCount: 5,
        createdAt: new Date("2024-01-15"),
    },
];
export async function seedDatabase(): Promise<void> {
    try {
        console.log("Начало наполнения базы данных...");
        const existingProducts = await productsAPI.getAll();
        if (existingProducts.length > 0) {
            console.log("✅ База данных уже наполнена");
            return;
            return;
        }
        await db.products.clear(););
        await db.users.clear();
        await db.cart.clear();
        await db.favorites.clear();
        await db.orders.clear();
        await db.reviews.clear();
        await db.reviews.clear();
        console.log("Добавление категорий...");
            await categoriesAPI.add(category);
        }
            await categoriesAPI.add(category);
        }
        console.log("Добавление продуктов...");
        }
            await productsAPI.add(product);
        }
        console.log("Добавление пользователей...");
        }
            await usersAPI.add(user);
        }
        console.log("Обновление счетчиков категорий...");
            const count = allProducts.filter(
                (p) => p.category === category.name,
            ).length;
            await categoriesAPI.update(category.id, { count });
        }
            await categoriesAPI.update(category.id, { count });
        }
        console.log("Установка настроек...");
            language: "ru",
            currency: "RUB",
        });
        console.log("База данных успешно наполнена!");
        console.log(`   Категорий: ${categories.length}`);
        console.log(`   Товаров: ${products.length}`);
        console.log(`   Пользователей: ${users.length}`);
    } catch (error) {
        console.error("Ошибка при наполнении базы данных:", error);
        throw error;
    }
}
    }
}
export async function resetDatabase(): Promise<void> {
        await db.delete();
        console.log("База данных сброшена");
        await seedDatabase();
        await db.delete();
        console.log("База данных сброшена");
        await seedDatabase();

